### ISSUE TITLE
it is not an issue just something cane be useful

### ISSUE THREAD

**Issue by salah-yousef** [dianavile/NeighbourhoodMap#1]
hi dianavile I am salah I knew you from Udacity Front end nano degree 
Today I just succeed to use github pages to host my react application so if you want to use it i call tell you how

**Comment by dianavile** [comment]
Hi salah-Yousef,

Yes, please. How did you manage to use GitHub pages to host your React app?
Hope to hear back from you. Thanks.

**Comment by salah-yousef** [comment]
Hi Dianavile ,,

https://github.com/ReactTraining/react-router/blob/dc7facf205f9ee43cebea9fab710dce036d04f04/FAQ.md


read this FAQ part
